Test KVDB API

diff --git a/.circleci/config (copy).yml b/.circleci/config (copy).yml
--- a/.circleci/config (copy).yml
+++ b/.circleci/config (copy).yml
@@ -78,9 +78,8 @@ commands:
               cd ~/project/backend
               npm install
               npm run migration:revert
-            fi            
+            fi
 jobs:
-
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -109,12 +108,12 @@ jobs:
           keys: [backend-build]
       - run:
           name: Back-end build
-          command: | 
-             # Your code here
-             #exit 1
-              cd backend
-              npm install
-              npm run build
+          command: |
+            # Your code here
+            #exit 1
+             cd backend
+             npm install
+             npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -207,14 +206,14 @@ jobs:
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
               --output text)
-            
+
             echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
             cat .circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      
+
       - destroy-environment
 
   configure-infrastructure:
@@ -247,13 +246,14 @@ jobs:
             cd backend
             npm install
             npm audit fix
+            npm audit fix --force
             npm i migrations > migrations_dump.txt
-
+            cat migrations_dump.txt
 
       - run:
           name: Send migration status to kvdb.io
           command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            if grep -q "has been executed successfully." /home/circleci/project/backend/migrations_dump.txt
             then
               curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
@@ -299,7 +299,7 @@ jobs:
       - checkout
       # Add ssh keys with fingerprint
       - add_ssh_keys:
-          fingerprints: ['be:60:c7:2b:6b:6a:19:82:62:8c:b9:36:59:7f:2e:63']
+          fingerprints: ["be:60:c7:2b:6b:6a:19:82:62:8c:b9:36:59:7f:2e:63"]
       # attach workspace
       - attach_workspace:
           at: ~/
@@ -329,9 +329,9 @@ jobs:
             cat inventory.txt
             export ANSIBLE_HOST_KEY_CHECKING=False
             ansible-playbook -i inventory.txt deploy-backend.yml
-      # Here's where you will add some code to rollback on failure 
+      # Here's where you will add some code to rollback on failure
       - revert-migrations
-      - destroy-environment 
+      - destroy-environment
   # deploy-backend:
   #   docker:
   #     - image: cimg/base:stable
@@ -367,7 +367,7 @@ jobs:
   #           cd .circleci/ansible
   #           cat inventory.txt
   #           ansible-playbook -i inventory.txt deploy-backend.yml
- 
+
   # deploy-backend:
   #   docker:
   #     - image: cimg/base:stable
